<div class="section_inwrapper">

    <div class="products_main row" style="padding: 20px 0; ">

    	<p class="title_ left">
    		<i class="material-icons left">edit</i>
        	Page adding
    	</p>
    	
    	<p style="clear: both; "></p>
    	<div class="col s6 formContainer">
    		<div class="progress"><div class="indeterminate"></div></div>
    	<?php 
	    	$form
	    		->setAttribute("action",$this->url("admin",["action" => "add-page"]))
	    		// ->setAttribute("id","pageadd")
	    		->prepare(); 

	    	echo $this->form()->openTag($form); 

	    		$e = $form->get("title"); 
	            echo "<div class='input-field col s12'>"; 
	            echo "<i class='material-icons prefix'>title</i>"; 
	            echo $this->formInput($e); 
	            echo $this->formLabel($e); 
	            echo "</div>";

	            $e = $form->get("short"); 
	            echo "<div class='input-field col s12'>"; 
	            echo "<i class='material-icons prefix'>description</i>"; 
	            echo $this->formInput($e); 
	            echo $this->formLabel($e); 
	            echo "</div>"; 

	            $e = $form->get("category"); 
	            echo "<div class='input-field col s12'><i class='material-icons prefix'>filter</i>";  
	            echo $this->formSelect($e); 
	            echo "</div>";
				
	            $e = $form->get("content"); 
	            echo "<div class='input-field col s12'>";  
	            echo $this->formTextarea($e); 
	            echo "</div>"; ?>


				<?php
					$e = $form->get("thumbnail"); 
					echo '<div class="file-field input-field clear" style="padding: 0 10px;"><div class="btn"><span><i class="material-icons left">add_a_photo</i>'; 
					echo "Thumbnail photo</span>";  
		            echo $this->formFile($e);

					echo '</div><div class="file-path-wrapper"><input class="file-path validate" type="text"></div></div>'; 
				?>
	            <button class="btn waves-effect left black" type="submit" style="margin: 0 0 0 10px;">
	            	Add page
	               <i class="material-icons left">save</i>
	            </button>
	    <?php 
	    	echo $this->form()->closeTag(); 
	     ?>
	     </div>

	     <script type="text/javascript">
	     	CKEDITOR.replace("content")
	     	CKEDITOR.replace = ("resolution",{height: 700})
	     </script>

	     
    </div>
</div>