<div class="section_inwrapper">

    <div class="products_main row" style="padding: 20px 0; ">

    	<p class="title_ left">
    		<i class="material-icons left">language</i>
        	Web site configuration
    	</p>
    	
    	<p style="clear: both; "></p>
    	<div class="col s6 formContainer">
    		<div class="progress"><div class="indeterminate"></div></div>
    	<?php 
	    	$form
	    		->setAttribute("action",$this->url("admin",["action" => "config"]))
	    		->setAttribute("id","config")
	    		->prepare(); 

		    	echo $this->form()->openTag($form); 

		    		$e = $form->get("title"); 
		            echo "<div class='input-field col s12'>"; 
		            echo "<i class='material-icons prefix'>title</i>"; 
		            echo $this->formInput($e); 
		            echo $this->formLabel($e); 
		            echo "</div>"; 

		            $e = $form->get("description"); 
		            echo "<div class='input-field col s12'>"; 
		            echo "<i class='material-icons prefix'>description</i>"; 
		            echo $this->formInput($e); 
		            echo $this->formLabel($e); 
		            echo "</div>"; 

		            $e = $form->get("mainPageText"); 
		            echo "<div class='input-field col s12'>"; 
		            echo "<i class='material-icons prefix'>language</i>"; 
		            echo $this->formInput($e); 
		            echo $this->formLabel($e); 
		            echo "</div>"; 

		            $e = $form->get("trusted"); 
		            echo "<div class='input-field col s12'>"; 
		            echo "<i class='material-icons prefix'>language</i>"; 
		            echo $this->formInput($e); 
		            echo $this->formLabel($e); 
		            echo "</div>"; 

		            $e = $form->get("trustedText"); 
		            echo "<div class='input-field col s12'>"; 
		            echo "<i class='material-icons prefix'>language</i>"; 
		            echo $this->formInput($e); 
		            echo $this->formLabel($e); 
		            echo "</div>"; 

		            $e = $form->get("email"); 
		            echo "<div class='input-field col s12'>"; 
		            echo "<i class='material-icons prefix'>email</i>"; 
		            echo $this->formInput($e); 
		            echo $this->formLabel($e); 
		            echo "</div>"; 

		            $e = $form->get("email2"); 
		            echo "<div class='input-field col s12'>"; 
		            echo "<i class='material-icons prefix'>email</i>"; 
		            echo $this->formInput($e); 
		            echo $this->formLabel($e); 
		            echo "</div>"; 

		            $e = $form->get("email3"); 
		            echo "<div class='input-field col s12'>"; 
		            echo "<i class='material-icons prefix'>email</i>"; 
		            echo $this->formInput($e); 
		            echo $this->formLabel($e); 
		            echo "</div>"; 

		            $e = $form->get("email4"); 
		            echo "<div class='input-field col s12'>"; 
		            echo "<i class='material-icons prefix'>email</i>"; 
		            echo $this->formInput($e); 
		            echo $this->formLabel($e); 
		            echo "</div>"; 

		            $e = $form->get("phone1"); 
		            echo "<div class='input-field col s12'>"; 
		            echo "<i class='material-icons prefix'>phone</i>"; 
		            echo $this->formInput($e); 
		            echo $this->formLabel($e); 
		            echo "</div>"; 

		            $e = $form->get("phone2"); 
		            echo "<div class='input-field col s12'>"; 
		            echo "<i class='material-icons prefix'>phone</i>"; 
		            echo $this->formInput($e); 
		            echo $this->formLabel($e); 
		            echo "</div>"; 

		            $e = $form->get("phone3"); 
		            echo "<div class='input-field col s12'>"; 
		            echo "<i class='material-icons prefix'>phone</i>"; 
		            echo $this->formInput($e); 
		            echo $this->formLabel($e); 
		            echo "</div>"; 

		            $e = $form->get("phone4"); 
		            echo "<div class='input-field col s12'>"; 
		            echo "<i class='material-icons prefix'>phone</i>"; 
		            echo $this->formInput($e); 
		            echo $this->formLabel($e); 
		            echo "</div>"; 

		            $e = $form->get("phone5"); 
		            echo "<div class='input-field col s12'>"; 
		            echo "<i class='material-icons prefix'>phone</i>"; 
		            echo $this->formInput($e); 
		            echo $this->formLabel($e); 
		            echo "</div>";

		            $e = $form->get("address"); 
		            echo "<div class='input-field col s12'>"; 
		            echo "<i class='material-icons prefix'>location_on</i>"; 
		            echo $this->formInput($e); 
		            echo $this->formLabel($e); 
		            echo "</div>"; 
		            ?>

		            <button class="btn waves-effect left black" type="submit">
		            	<i class="material-icons left">save</i>
		            	Save changes
		            </button>
			    <?php  echo $this->form()->closeTag(); ?>
	    	</div>
    </div>
</div>