<div class="section_inwrapper">

    <div class="products_main row" style="padding: 20px 0; ">

    	<p class="title_ left">
    		<i class="material-icons left">edit</i>
        	Page editing
    	</p>
    	
    	<p style="clear: both; "></p>
    	<div class="col s6 formContainer">
    		<div class="progress"><div class="indeterminate"></div></div>
    	<?php 
	    	$form
	    		->setAttribute("action",$this->url("admin",["action" => "edit-page"]))
	    		->setAttribute("id","pageedit")
	    		->prepare(); 

	    	echo $this->form()->openTag($form); 

	    		$e = $form->get("title"); 
	            echo "<div class='input-field col s12'>"; 
	            echo "<i class='material-icons prefix'>title</i>"; 
	            echo $this->formInput($e); 
	            echo $this->formLabel($e); 
	            echo "</div>"; 

	            $e = $form->get("short"); 
	            echo "<div class='input-field col s12'>"; 
	            echo "<i class='material-icons prefix'>description</i>"; 
	            echo $this->formInput($e); 
	            echo $this->formLabel($e); 
	            echo "</div>"; 

	            $e = $form->get("category"); 
	            echo "<div class='input-field col s12'><i class='material-icons prefix'>filter</i>";  
	            echo $this->formSelect($e); 
	            echo "</div>";
				
	            $e = $form->get("content");
	            echo "<div class='input-field col s12'>";
	            echo $this->formTextarea($e);
	            echo "</div>";
	    
				$e = $form->get("thumbnail"); 
				echo '<div class="file-field input-field clear" style="padding: 0 10px;"><div class="btn"><span><i class="material-icons left">add_a_photo</i>'."Thumbnail photo</span>";  
	            echo $this->formFile($e); 
				echo '</div><div class="file-path-wrapper"><input class="file-path validate" type="text"></div></div>'; ?>

	            <button class="btn waves-effect left black" type="submit" style="margin: 0 0 0 10px;">
	            	Save changes
	               <i class="material-icons left">save</i>
	            </button>
	    <?php echo $this->form()->closeTag(); ?>
	     </div>
	    <div class="col s6">
	    	<b class="left">Strict size: 450X300</b>
	    	<p class="clear"></p>
	    	<?php if($page->getThumbnail()): ?>
		    	<img src="<?php echo $this->basePath("img/{$page->getThumbnail()}") ?>" width="100%" data-id="<?php echo $page->getId() ?>">
		    	<p class="clear"></p>
		    	<!-- <button class="btn black addImg" data-page-id="<?php echo $page->getId() ?>" for="thumbnail">Change</button> -->
		    	<a class="btn black delImg" data-page-id="<?php echo $page->getId() ?>" data-del-img="<?php echo $page->getThumbnail() ?>">Delete</a>
		    <?php else: ?>
		    	<img src="<?php echo $this->basePath("img/noPhoto.jpg") ?>" height="300">
		    	<!-- <p class="clear"></p> -->
		    	<!-- <button class="btn black addImg" data-pageId="<?php echo $page->getId() ?>" for="thumbnail">Add thumbnail</button> -->
		    <?php endif; ?>
	    </div>

		<form class="hide upload">
			<input type="file" name="file" id="file">
		</form>
	    <div class="col s6 grid" style="padding: 10px 5px;">
	    	<?php 
	    		$files = scandir("./public/img");
	    		unset($files[0],$files[1]);
	    		foreach($files as $key => $value){
	    			if(!preg_match("/\./", $value)) unset($files[$key]);
	    		}
	    		if($files): ?>
		    	<div class="grid-item">
		    		<a class="addpage cursor add" style="height: 150px;">
			    		<i class="material-icons" style="line-height: 150px;">add</i>	
		    		</a>
		    	</div>
    			<?php foreach($files as $key => $file): ?>
		    	<div class="grid-item">
		    		<div class="copyImg cursor" value="http://st/img/<?php echo $file ?>">
			    		<img src="<?php echo $this->basePath("img/{$file}") ?>" width="100%">
		    		</div>
		    	</div>
		    	<?php endforeach; endif; ?>
	    </div>

	     <input type="hidden" id="pageId" value="<?php echo $page->getId() ?>">
	     <script type="text/javascript">
	     	CKEDITOR.replace("content")
	     	CKEDITOR.replace = ("resolution",{height: 700})
	     </script>

	     
    </div>
</div>