<!-- PAGE HEADER -->
<div class="pageheader">
	<img src="<?php echo $this->basePath("job.jpg") ?>">
	<h1 class="bold uppercase">
		<?php echo $page->getTitle() ?>
	</h1>
</div>
<!-- !PAGE HEADER -->

<!-- PAGE CONTENT -->
<div class="mw pagecontent">
	<h2>
		<?php echo $page->getShort() ?>
	</h2>
	
	<div class="border mg"></div>
	
	<?php echo $page->getContent() ?>
	
</div>

<div class="mw" style="margin-top: -166px; overflow: hidden">
	<div class="grid">
		<?php if($result): foreach ($result as $key => $value): ?>
			<div class="grid-item" style="width: 25%;">
				<a href="<?php echo $this->url("main",["action" => "apply-for-job","id" => $value->getId()]) ?>" class="waves-effect">
			        <img src="<?php echo $this->basePath("/img/{$value->getThumbnail()}") ?>" width="100%">
					<p class="st bk white-text">
						<?php echo $value->getTitle() ?> >>
					</p>
				</a>
			</div>
		<?php endforeach; endif; ?>
	</div>

</div>
<!-- !PAGE CONTENT -->