<!-- PAGE HEADER -->
<div class="pageheader">
	<img src="<?php echo $this->basePath("job.jpg") ?>">
	<h1 class="bold uppercase">
		<?php echo $page->getTitle() ?>
	</h1>
</div>
<!-- !PAGE HEADER -->

<?php if($page->getId() == 12 || $page->getId() == 13): ?>
	<div class="white mw row apply" style="margin-top: -60px;  max-width: 750px; padding: 40px; overflow: hidden; position: relative; z-index: 99; ">

		<div class="col s12">
	    	<p>
	    		<i class="material-icons left">star</i>
	    		Please give us detailed info about yourself to have more chance to be employed
	    	</p>
	    </div>
    	<div class="col s12 formContainer">
    		<div class="progress hide"><div class="indeterminate"></div></div>
    	<?php 
	    	$form
	    		->setAttribute("action",$this->url("main",["action" => "apply-for-job","id" => 12]))
	    		->prepare(); 

	    	echo $this->form()->openTag($form); 

	    		$e = $form->get("name"); 
	            echo "<div class='input-field col s12'>"; 
	            echo "<i class='material-icons prefix'>title</i>"; 
	            echo $this->formInput($e); 
	            echo $this->formLabel($e); 
	            echo "</div>";

	            $e = $form->get("last_name");
	            echo "<div class='input-field col s12'>";
	            echo "<i class='material-icons prefix'>description</i>";
	            echo $this->formInput($e);
	            echo $this->formLabel($e);
	            echo "</div>";

	    		$e = $form->get("cell");
	            echo "<div class='input-field col s12'>";
	            echo "<i class='material-icons prefix'>phone</i>";
	            echo $this->formInput($e);
	            echo $this->formLabel($e);
	            echo "</div>";

	            $e = $form->get("email");
	            echo "<div class='input-field col s12'>";
	            echo "<i class='material-icons prefix'>email</i>";
	            echo $this->formInput($e);
	            echo $this->formLabel($e);
	            echo "</div>";

	            $e = $form->get("cat"); 
	            echo "<div class='input-field col s12'><i class='material-icons prefix'>filter</i>";  
	            echo $this->formSelect($e); 
	            echo "</div>";
	            ?>

				<?php
				$e = $form->get("cv"); 
				echo '<div class="file-field input-field clear" style="padding: 0 10px;"><div class="btn waves-effect" style="background: rgba(192,20,30,1)"><span><i class="material-icons left">attach_file</i>'; 
				echo "Attach resume (PDF only)</span>";  
	            echo $this->formFile($e);

				echo '</div><div class="file-path-wrapper"><input class="file-path validate" type="text"></div></div>'; 
				?>
	            <button class="btn waves-effect waves-light right black" type="submit" style="margin: 0 0 0 10px;">
	               <i class="material-icons right">send</i>
	            	Send information
	            </button>
		    <?php echo $this->form()->closeTag(); ?>
	    </div>

	    

	</div>
<?php endif; ?>