<!-- PAGE HEADER -->
<div class="pageheader">
	<img src="<?php echo $this->basePath("job.jpg") ?>">
	<h1 class="bold">
		APPLY FOR JOB
	</h1>
</div>
<!-- !PAGE HEADER -->

<!-- PAGE CONTENT -->
<div class="mw pagecontent">
	<h2>
		Our company always needs drivers and energetic operators for dispatch
	</h2>
	<div class="border mg"></div>

	<div class="grid">
		<div class="grid-item orange"  style="height: 200px;">
			Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
			tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
			quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
			consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
			cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
			proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
		</div>
	</div>
	
</div>
<!-- !PAGE CONTENT -->