<!--PAGE HEADER -->
<div class="pageheader">
	<img src="<?php echo $this->basePath("contact.jpg") ?>">
	<h1 class="bold uppercase">
		Contacts
		<?php //echo $page->getTitle() ?>
	</h1>
</div>
<!-- !PAGE HEADER -->

<!-- PAGE CONTENT -->
<div class="mw row pagecontent contacts">
	<h2 class="bold">
		<?php echo $this->layout()->config->getTitle() ?>
	</h2>
	<span>
		<i class="material-icons left">location_on</i>
		<?php echo $this->layout()->config->getAddress() ?>
	</span>
	<p class="clear border" style="margin: 40px 0 40px;"></p>
	
	<!-- MAP -->
	<div class="col s6">
		<a target="blank" href="https://www.google.com/maps/place/843+Pontiac+Ct+%23625,+Aurora,+IL+60502,+USA/@41.7685276,-88.2459248,17z/data=!3m1!4b1!4m5!3m4!1s0x880ef98ae03a4bcb:0x20db72ecc6a14ba9!8m2!3d41.7685236!4d-88.2437361?hl=en" class="viewonmap">
			<img src="<?php echo $this->basePath("address.png") ?>" class="right" width="100%">
			<i class="material-icons">add</i>
		</a>
	</div>
	<!-- !MAP -->

	<div class="callus col s6">
		<p class="bold">
			<i class="material-icons left">phone</i>
			Call us
		</p> 
		<ul class="nolist" style="padding-top: 0;">
			<?php if($phone = $this->layout()->config->getPhone1()): ?>
				<li>
					<?php
	                    $phone = $this->layout()->config->getPhone1();
	                    $ar = preg_split("#/#", $phone);
	                ?>
	                <span class="left"><?php echo $ar[0] ?>:</span>
	                <a href="callto:<?php echo $ar[1] ?>">
	                    <?php echo $ar[1] ?>
	                </a>
				</li>
			<?php endif; ?>
			<?php if($this->layout()->config->getPhone2()): ?>
				<li>
					<?php
	                    $phone2 = $this->layout()->config->getPhone2();
	                    $ar = preg_split("#/#", $phone2);
	                ?>
	                <span class="left"><?php echo $ar[0] ?>:</span>
	                <a href="callto:<?php echo $ar[1] ?>">
	                    <?php echo $ar[1] ?>
	                </a>
				</li>
			<?php endif; ?>
			<?php if($this->layout()->config->getPhone3()): ?>
				<li>
					<?php
	                    $phone3 = $this->layout()->config->getPhone3();
	                    $ar = preg_split("#/#", $phone3);
	                ?>
	                <span class="left"><?php echo $ar[0] ?>:</span>
	                <a href="callto:<?php echo $ar[1] ?>">
	                    <?php echo $ar[1] ?>
	                </a>
				</li>
			<?php endif; ?>
			<?php if($this->layout()->config->getPhone4()): ?>
				<li>
					<?php
	                    $phone4 = $this->layout()->config->getPhone4();
	                    $ar = preg_split("#/#", $phone4);
	                ?>
	                <span class="left"><?php echo $ar[0] ?>:</span>
	                <a href="callto:<?php echo $ar[1] ?>">
	                    <?php echo $ar[1] ?>
	                </a>
				</li>
			<?php endif; ?>
			<?php if($this->layout()->config->getPhone5()): ?>
				<li>
					<?php
	                    $phone5 = $this->layout()->config->getPhone5();
	                    $ar = preg_split("#/#", $phone5);
	                ?>
	                <span class="left"><?php echo $ar[0] ?>:</span>
	                <a href="callto:<?php echo $ar[1] ?>">
	                    <?php echo $ar[1] ?>
	                </a>
				</li>
			<?php endif; ?>
		</ul>
		<div class="clear" style="margin: 20px 0; max-width: 270px;"></div>
		<p class="bold">
			<i class="material-icons left">email</i>
			Mail us
		</p>
		<ul>
			<?php if($this->layout()->config->getEmail()): ?>
				<li>
					<?php
	                    $email = $this->layout()->config->getEmail();
	                    $ar = preg_split("#/#", $email);
	                ?>
	                <span class="left"><?php echo $ar[0] ?>:</span>
	                <a href="callto:<?php echo $ar[1] ?>">
	                    <?php echo $ar[1] ?>
	                </a>
				</li>
			<?php endif; ?>
			<?php if($this->layout()->config->getEmail2()): ?>
				<li>
					<?php
	                    $email2 = $this->layout()->config->getEmail2();
	                    $ar = preg_split("#/#", $email2);
	                ?>
	                <span class="left"><?php echo $ar[0] ?>:</span>
	                <a href="callto:<?php echo $ar[1] ?>">
	                    <?php echo $ar[1] ?>
	                </a>
				</li>
			<?php endif; ?>
			<?php if($this->layout()->config->getEmail3()): ?>
				<li>
					<?php
		                $email3 = $this->layout()->config->getEmail3();
		                $ar = preg_split("#/#", $email3);
		            ?>
		            <span class="left"><?php echo $ar[0] ?>:</span>
		            <a href="callto:<?php echo $ar[1] ?>">
		                <?php echo $ar[1] ?>
		            </a>
				</li>
			<?php endif; ?>
			<?php if($this->layout()->config->getEmail4()): ?>
				<li>
					<?php
	                    $email4 = $this->layout()->config->getEmail4();
	                    $ar = preg_split("#/#", $email4);
	                ?>
	                <span class="left white-text"><?php echo $ar[0] ?>:</span>
	                <a href="callto:<?php echo $ar[1] ?>">
	                    <?php echo $ar[1] ?>
	                </a>
				</li>
			<?php endif; ?>
		</ul>
	</div>
	<!-- !ADDRESS -->
</div>
<!-- !PAGE CONTENT -->