<!--PAGE HEADER -->
<div class="pageheader">
	<img src="<?php echo $this->basePath("contact.jpg") ?>">
	<h1 class="bold">
		CONTACTS
	</h1>
</div>
<!-- !PAGE HEADER -->

<!-- PAGE CONTENT -->
<div class="mw row pagecontent contacts">
	<h2 class="bold">
		"ST MARK OF ORLANDO" llc
	</h2>
	<span>
		<i class="material-icons left">location_on</i>
		843 Pontiac CT Unit 625, Aurora, IL 60502
	</span>
	<p class="clear border" style="margin: 40px 0 40px;"></p>
	
	<!-- MAP -->
	<div class="col s6">
		<a target="blank" href="https://www.google.com/maps/place/843+Pontiac+Ct+%23625,+Aurora,+IL+60502,+USA/@41.7685276,-88.2459248,17z/data=!3m1!4b1!4m5!3m4!1s0x880ef98ae03a4bcb:0x20db72ecc6a14ba9!8m2!3d41.7685236!4d-88.2437361?hl=en" class="viewonmap">
			<img src="<?php echo $this->basePath("address.png") ?>" class="right" width="100%">
			<i class="material-icons">add</i>
		</a>
	</div>
	<!-- !MAP -->

	<div class="callus col s6">
		<p class="bold">
			<i class="material-icons left">phone</i>
			Call us
		</p> 
		<ul class="nolist" style="padding-top: 0;">
			<li><p>Dispatch main: <a href="">407-917-3695</a></p></li>
			<li><p>Dispatch: <a href="">407-917-4239</a></p></li>
			<li><p>Dispatch: <a href="">630-793-6600</a></p></li>
			<li><p>Safety: <a href="">239-287-8537</a></p></li>
			<li><p>Safety: <a href="">702-209-2545</a></p></li>
		</ul>
		<div class="clear" style="margin: 20px 0; max-width: 270px;"></div>
		<p class="bold">
			<i class="material-icons left">email</i>
			Mail us
		</p>
		<ul>
			<li>
				<span><a href="">info@stmarkoforlando.com</a></span>
			</li>
		</ul>
	</div>
	<!-- !ADDRESS -->
</div>
<!-- !PAGE CONTENT -->