PAGE HEADER -->
<div class="pageheader">
	<img src="<?php echo $this->basePath("contact.jpg") ?>">
	<h1 class="bold">
		CONTACTS
	</h1>
</div>
<!-- !PAGE HEADER -->

<!-- PAGE CONTENT -->
<div class="mw row pagecontent contacts">

	<!-- MAP -->
	<!-- <div class="col s6">
		<img src="<?php echo $this->basePath("map.jpg") ?>" class="right" width="100%">
		<a href="" class="btn waves-effect black waves-light right" style="margin-top: 10px;">
			<i class="material-icons left">location_on</i>
			View on map
		</a>
	</div> -->
	<!-- !MAP -->

	<!-- ADDRESS -->
	<!-- <div class="callus col s6" style="padding-left: 40px;">
		<p class="bold" style="margin: 0 0 10px;">Address</p>
		<span>
			<i class="material-icons left">location_on</i>
			843 Pontiac CT Unit 625, Aurora, IL 60502
		</span>
		<div class="border clear" style="margin: 10px 0; max-width: 360px;"></div>
		<p class="bold">Call us</p> 
		<ul class="nolist" style="padding-top: 0;">
			<li>
				<p>
					<i class="material-icons left">phone</i>
					Dispatch main: 
					<a href="">407-917-3695</a>
				</p>
			</li>
			<li>
				<p>
					<i class="material-icons left">phone</i>
					Dispatch: 
					<a href="">407-917-4239</a>
				</p>
			</li>
			<li>
				<p>
					<i class="material-icons left">phone</i>
					Dispatch:
					<a href="">630-793-6600</a>
				</p>
			</li>
			<li>
				<p>
					<i class="material-icons left">phone</i>
					Safety: 
					<a href="">239-287-8537</a>
				</p>
			</li>

			<li>
				<p>
					<i class="material-icons left">phone</i>
					Safety: 
					<a href="">702-209-2545</a>
				</p>
			</li>
			<li style="margin: 5px 0;">
				<p>
				</p>
			</li>
		</ul>
		<div class="border clear" style="margin: 10px 0; max-width: 270px;"></div>
		<p class="bold">Mail us</p>
		<span>
			<a href="">
				<i class="material-icons left">email</i>
				info@stmarkoforlando.com
			</a>
			
		</span>
	</div> -->
	<!-- !ADDRESS -->

	<p class="clear" style="margin: 40px 0"></p>

	<!-- MESSAGING -->
	<div class="col s6">
		<p class="cont_t bold">Send us message</p>
	    <form class="col s12 contact_form ">
	    	<div class="row">
		        <div class="progress indeterminated hide"></div>
		        <div class="input-field col s12">
		        	<i class="material-icons prefix">account_circle</i>
		        	<input id="first_name" type="text" required>
		        	<label for="first_name">Name</label>
		        </div>
		        
		        <div class="input-field col s6">
		        	<i class="material-icons prefix">phone</i>
		        	<input id="last_name" type="text" required>
		        	<label for="last_name">Phone</label>
		        </div>

		        <div class="input-field col s6">
		        	<i class="material-icons prefix">email</i>
		        	<input id="first_name" type="text" required>
		        	<label for="first_name">Email</label>
		        </div>
		        
		        <div class="input-field col s12">
		        	<i class="material-icons prefix">message</i>
		          <textarea id="textarea1" class="materialize-textarea" required></textarea>
		          <label for="textarea1">Message</label>
		        </div>

	      	</div>
	      	<button class="btn waves-effect waves-light black right">
	      		<i class="material-icons right">send</i>
	      		send message
	      	</button>
	    </form>
	</div>
	<p class="clear"></p>
</div>
<!-- !PAGE CONTENT -->