<!-- SLIDER -->
        <div id="slider">
            <img src="<?php echo $this->basePath("/18042304_main_1200.jpg") ?>">
            <div id="div">
                <h1>
                    'St Mark of Orlando' <span style="opacity: .5;">LLC</span>
                </h1>
                <p>
                    Logistics company, Aurora IL
                </p>
                <a href="<?php echo $this->url("main",["action" => "logistic-services"]) ?>" class="btn waves-effect more orange black-text bold">
                    <i class="material-icons right">add</i>
                    More about logistics
                </a>
            </div>
        </div>
        <!-- !SLIDER -->
        
        <!-- TRUSTED BY #trustedBy -->
        <div class="white">
            <div class="trusted overflow">
                <a class="left">Trusted by</a>
                <ul class="clear">
                    <li>
                        <a><img src="<?php echo $this->basePath("img/bmw.png") ?>"></a>
                    </li>
                    <li>
                        <a><img src="<?php echo $this->basePath("img/toyota.png") ?>"></a>
                    </li>
                    <li>
                        <a><img src="<?php echo $this->basePath("img/fedex.png") ?>"></a>
                    </li>
                    <li>
                        <a><img src="<?php echo $this->basePath("img/bestbuy.png") ?>"></a>
                    </li>
                    <li>
                        <a><img src="<?php echo $this->basePath("img/apple.png") ?>"></a>
                    </li>
                    <li>
                        <a><img src="<?php echo $this->basePath("img/mazda.png") ?>"></a>
                    </li>
                    <li>
                        <a><img src="<?php echo $this->basePath("img/t.png") ?>"></a>
                    </li>
                    <li>
                        <a><img src="<?php echo $this->basePath("img/a.png") ?>"></a>
                    </li>
                </ul>
            </div>
        </div>
        <!-- !TRUSTED -->

        <div class="row mw services" style="margin: 60px auto;">
            <div class="main_div clear">
                <div class="col s4 main_divs">
                    <a class="left service">
                        <span>Service</span>
                        <img src="<?php echo $this->basePath("EFS_CC_PFJjbHunt_Promo.jpg") ?>" width="100%">
                    </a>
                </div>
                <div class="col s4 main_divs">
                    <a class="left service">
                        <span>Service</span>
                        <img src="<?php echo $this->basePath("EFS_CC_PFJjbHunt_Promo.jpg") ?>" width="100%">
                    </a>
                </div>
                <div class="col s4 main_divs">
                    <a class="left service">
                        <span>Service</span>
                        <img src="<?php echo $this->basePath("EFS_CC_PFJjbHunt_Promo.jpg") ?>" width="100%">
                    </a>
                </div>
                <div class="col s4 main_divs">
                    <a class="left service">
                        <span>Service</span>
                        <img src="<?php echo $this->basePath("EFS_CC_PFJjbHunt_Promo.jpg") ?>" width="100%">
                    </a>
                </div>
                <div class="col s4 main_divs">
                    <a class="left service">
                        <span>Service</span>
                        <img src="<?php echo $this->basePath("EFS_CC_PFJjbHunt_Promo.jpg") ?>" width="100%">
                    </a>
                </div>
                <div class="col s4 main_divs">
                    <a class="left service">
                        <span>Service</span>
                        <img src="<?php echo $this->basePath("EFS_CC_PFJjbHunt_Promo.jpg") ?>" width="100%">
                    </a>
                </div>
            </div>
        </div>