<!-- PAGE HEADER -->
<div class="pageheader">
	<img src="<?php echo $this->basePath("l.jpg") ?>">
	<h1 class="bold uppercase">
		<?php echo $page->getTitle() ?>
	</h1>
</div>
<!-- !PAGE HEADER -->

<!-- PAGE CONTENT -->
<div class="mw pagecontent" style="position: relative;">
	<a href="<?php echo $this->url("main",["action" => "services"]) ?>" class="btn bk" style="position: absolute; top: -45px; left: 0;">
		<i class="material-icons left">arrow_back</i>
		All services
	</a>

	<?php echo $page->getContent() ?>
	
</div>
<!-- !PAGE CONTENT -->