PAGE HEADER -->
<div class="pageheader">
	<img src="<?php echo $this->basePath("l.jpg") ?>">
	<h1 class="bold uppercase">
		<?php echo $page->getTitle() ?>
	</h1>
</div>
<!-- !PAGE HEADER -->

<!-- PAGE CONTENT -->
<!--<div class="mw pagecontent">

	<?php echo $page->getContent() ?>
	
</div> -->
<div class="mw" style="margin-top: -60px; overflow: hidden;">
	<div class="grid">
		<?php
			if($services): foreach ($services as $key => $value):
		?>
			<div class="grid-item" style="width: 25%;">
				<a href="<?php echo $this->url("main",["action" => "services","id" => $value->getId()]) ?>" class="waves-effect">
			        <img src="<?php echo $this->basePath("/img/{$value->getThumbnail()}") ?>" width="100%">
					<p class="st bk white-text">
						<?php echo $value->getTitle() ?>
					</p>
				</a>
			</div>
		<?php endforeach; endif; ?>
		
	</div>

</div>
<!-- !PAGE CONTENT -->