<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('St Mark of Orlando LLC')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/admin.css'))
            ->prependStylesheet($this->basePath('css/materialize.min.css'))
            ->prependStylesheet($this->basePath('dist/css/AdminLTE.min.css'))
            ->prependStylesheet($this->basePath('dist/css/skins/_all-skins.min.css'))
        ?>
        <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
        <?= $this->headScript()
            ->prependFile($this->basePath('js/admin.js'))
            ->prependFile($this->basePath('js/jquery.flexslider.js'))
            ->prependFile($this->basePath('js/lightbox.js'))
            ->prependFile($this->basePath('js/materialize.min.js'))
            ->prependFile($this->basePath('js/masonry.pkgd.js'))
            ->prependFile($this->basePath('ckeditor/ckeditor.js'))
        ?>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed:400,400i,700,700i" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Oswald" rel="stylesheet">
    </head>
    <body class="skin-blue" data-spy="scroll" data-target="#scrollspy">
      <div class="wrapper">

        <header class="main-header">
          <!-- Logo -->
          <a href="<?php echo $this->url("home") ?>" class="logo">
            <!-- mini logo for sidebar mini 50x50 pixels -->
            <span class="logo-mini"><b>A</b>LT</span>
            <!-- logo for regular state and mobile devices -->
            <span class="logo-lg">ST MARK</span>
          </a>
          <!-- Header Navbar: style can be found in header.less -->
          <nav class="navbar navbar-static-top" role="navigation">
            <!-- Navbar Right Menu -->
          </nav>
        </header>
        <!-- Left side column. contains the logo and sidebar -->
        <aside class="main-sidebar">
          <!-- sidebar: style can be found in sidebar.less -->
          <div class="sidebar" id="scrollspy">

            <!-- sidebar menu: : style can be found in sidebar.less -->
            <ul class="nav sidebar-menu">
              <li>
                <a href="<?php echo $this->url("admin") ?>">
                  <i class="fa fa-circle-o"></i>
                  Introduction
                </a>
              </li>
              <li>
                <a href="<?php echo $this->url("admin",["action"=>"config"]) ?>">
                  <i class="fa fa-circle-o"></i>
                  Website config
                </a>
              </li>
              <li>
                <a href="<?php echo $this->url("admin",["action" => "pages"]) ?>"><i class="fa fa-circle-o"></i>
                  Pages
                </a>
              </li>
              <li>
                <a href="#" class="logout"><i class="fa fa-circle-o"></i>
                  Logout
                </a>
              </li>
            </ul>
          </div>
          <!-- /.sidebar -->
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
          <!-- Main content -->
          <div class="content body">
            
              <?php echo $this->content ?>

          </div><!-- /.content -->
        </div><!-- /.content-wrapper -->


        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
          <!-- Create the tabs -->
          <div class="pad">
            This is an example of the control sidebar.
          </div>
        </aside><!-- /.control-sidebar -->
        <!-- Add the sidebar's background. This div must be placed
             immediately after the control sidebar -->
        <div class="control-sidebar-bg"></div>

    </div><!-- ./wrapper -->

        </body>
        <?= $this->inlineScript() ?>
</html>
