<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('St Mark of Orlando LLC')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/materialize.min.css'))
            ->prependStylesheet($this->basePath('css/flexslider.css'))
            ->prependStylesheet($this->basePath('css/lightbox.css'))
        ?>
        <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
        <?= $this->headScript()
            ->prependFile($this->basePath('js/jquery.flexslider.js'))
            ->prependFile($this->basePath('js/lightbox.js'))
            ->prependFile($this->basePath('js/materialize.min.js'))
            ->prependFile($this->basePath('js/masonry.pkgd.js'))
            ->prependFile($this->basePath('js/1.js'))
        ?>
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=PT+Sans" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Oswald" rel="stylesheet">
    </head>
    <body>
        <header>
            <div>
                <a href="<?php echo $this->url("home") ?>" id="logo" class="left <?php if(isset($this->layout()->hp)) echo "red-text active_logo" ?>"></a>
                <?php 
                    $partialMenu = array('layout/topnav.phtml','default');
                    $this->navigation('navigation')->menu()->setPartial($partialMenu);  
                    echo $this->navigation("navigation");  
                ?>
            </div>
        </header>
        <a class="open_menu"></a>

        <?php echo $this->content ?>

        <footer>
            <div class="row" style="margin-bottom: 0;">

                <!-- CONTACTS -->
                <div class="col s4">
                    <ul>
                        <li>
                            <p>
                                <i class="material-icons left">phone</i>
                                Contact us
                            </p>
                        </li>
                        <li>
                            <span class="left white-text">Main line:</span><a href="">1-800-222-1234</a>
                        </li>
                        <li>
                            <span class="left white-text">Dispatch: </span><a href="">1-800-222-1234</a>
                        </li>
                        <li>
                            <span class="left white-text">Accounting: </span><a href="">1-800-222-1234</a>
                        </li>
                    </ul>

                    <ul style="padding-bottom: 0;">
                        <li>
                            <p>
                                <i class="material-icons left">email</i>
                                Email us
                            </p>
                        </li>
                        <li>
                            <span class="left white-text">Main email: </span><a href="">stmarkoforlando@gmail.com</a>
                        </li>
                        <li>
                            <span class="left white-text">Team: </span> <a href="">stmark.team@gmail.com</a>
                        </li>
                    </ul>
                </div>
                <!-- !CONTACTS -->

                <!-- PAGES -->
                <div class="col s4">
                    <ul>
                        <li>
                            <p>
                                <i class="material-icons left">filter</i>
                                All pages
                            </p>
                        </li>
                        <li>
                            <a href="">Logistics Services</a>
                        </li>
                        <li>
                            <a href="">Apply for job</a>
                        </li>
                        <li>
                            <a href="">Resources</a>
                        </li>
                        <li>
                            <a href="">Contacts</a>
                        </li>
                        <li>
                            <a href="">Enter site</a>
                        </li>
                    </ul>
                </div>
                <!-- !PAGES -->

                <!--  -->
                <div class="col s4">
                    
                </div>
            </div>
        </footer>
    </body>
        <?= $this->inlineScript() ?>
</html>
