<ul class="nolist menu center-align">
	<?php
	foreach ($this->container as $page):
	?>
		<li>
			<a href="
				<?php 
	    			echo $page->getHref()
				?>
			"
			<?php if($page->isActive()) echo "class='page_active'" ?>
			<?php 
			if (!empty($page->pages))
			{
			    foreach ($page->pages as $subpage) 
			    {
			        if ($subpage->isActive()) echo "class='page_active'";
			    }
			}
			?>
	>
				<?php if($page->icon): ?>
					<i class="material-icons left"><?=$page->icon?></i>
				<?php endif;  ?>

				<?php // show the count of items of the cart ?>
				<?php if($page->getHref() == "/cart"):  ?>
					<span class="countContainer">
					<?php if(isset($this->layout()->totalItems)): ?>
		                <span class="badge cartItems"><?= $this->layout()->totalItems; ?></span>
		            <?php endif;  ?>
		            </span>
	            <?php endif;  ?>

				<span><?php echo $page->label?></span>
			</a>
		</li>	    	
	<?php endforeach; ?>
</ul>