                    <?php //echo "<pre>".print_r($products,1)."</pre>";  ?>
<div class="section_inwrapper">
    <div class="products_main row" style="padding: 0px 0 20px;  ">
	<h1>Registration</h1>

    	<div class="col s6 formContainer cont">
	        <div class="progress"><div class="indeterminate"></div></div>

	        <?php 
	        	$form->setAttribute("action",$this->url("user",["action" => "signup"])); 
	        	$form->prepare(); 

	        	echo $this->form()->openTag($form); 

	        		$e = $form->get("nick"); 
		            echo "<div class='input-field col s12'>"; 
		            echo "<i class='material-icons prefix'>person</i>"; 
		            echo $this->formInput($e); 
		            echo $this->formLabel($e); 
		            echo "</div>"; 

		            $e = $form->get("email"); 
		            echo "<div class='input-field col s12'>"; 
		            echo "<i class='material-icons prefix'>email</i>"; 
		            echo $this->formInput($e); 
		            echo $this->formLabel($e); 
		            echo "</div>"; 

		            $e = $form->get("pass"); 
		            echo "<div class='input-field col s12'>"; 
		            echo "<i class='material-icons prefix'>security</i>"; 
		            echo $this->formInput($e); 
		            echo $this->formLabel($e); 
		            echo "</div>"; 

		            $e = $form->get("rpass"); 
		            echo "<div class='input-field col s12'>"; 
		            echo "<i class='material-icons prefix'>repeat</i>"; 
		            echo $this->formInput($e); 
		            echo $this->formLabel($e); 
		            echo "</div>"; 

		            //
		    ?>
		    		<p style="clear: both; padding: 7.7px 0;"></p>
		            <button class="btn waves-effect left " type="submit">Submit
		               <i class="material-icons right">send</i>
		            </button>
		    <?php 
	        	echo $this->form()->closeTag(); 
	         ?>
         </div>

         <div class="col s6" style="padding-left: 20px; ">
         	<a class="waves-effect btn" href="<?php echo $this->url("user",["action" => "signin"]) ?>">
		       <!--  <i class="material-icons left">arrow_back</i> -->
		        Signin
			</a>
         </div>

    </div><!-- !.products_main -->

</div><!-- !.section_inwrapper -->